# Generated by Django 4.2.1 on 2023-05-29 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline_reservation_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrators',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airline_companies',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='airline_reservation_system.countries'),
        ),
        migrations.AlterField(
            model_name='airline_companies',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flights',
            name='airline_company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airline_reservation_system.airline_companies'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='destination_country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_destination', to='airline_reservation_system.countries'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='origin_country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_origin', to='airline_reservation_system.countries'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airline_reservation_system.customers'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airline_reservation_system.flights'),
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together={('flight_id', 'customer_id')},
        ),
    ]
