# Generated by Django 4.2.1 on 2023-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_reservation_system', '0003_alter_countries_flag_alter_users_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='flag',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='upload_img/country_flags/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='users',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='./web-design/upload_img/user_thumbnails/', width_field='width'),
        ),
    ]
