# Generated by Django 4.2.1 on 2023-06-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_reservation_system', '0005_alter_countries_flag_alter_users_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='./web-design/upload_img/user_flags/'),
        ),
    ]
