# Generated by Django 4.2.1 on 2023-06-26 12:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airline_reservation_system', '0007_alter_countries_flag_alter_users_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='flag',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=False, null=True, quality=75, scale=0.5, size=[240, 180], upload_to='./web-design/upload_img/user_flags/'),
        ),
    ]
