# Generated by Django 4.2.1 on 2023-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_reservation_system', '0008_alter_countries_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_companies',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
