# Generated by Django 4.2.1 on 2023-12-11 19:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airline_reservation_system', '0020_alter_users_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=75, scale=0.5, size=[500, None], upload_to='./web-design/upload_img/user_thumbnails/'),
        ),
    ]
